In [1]:
from sqlalchemy import create_engine
import tkinter
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

#imports
#numpy,pandas,scipy, math, matplotlib
import numpy as np
import pandas as pd
import scipy
from math import sqrt
import matplotlib.pyplot as plt
#estimators
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
#model metrics
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
#cross validation
#from sklearn.cross_validation import train_test_split 
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import load_digits

In [2]:
#importing csv file from task 2
rawData= pd.read_csv('cleancredit.csv', header = 1)

In [3]:
rawData.head()

ID  LIMIT_BAL     SEX   EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0   1      20000  female  university         1   24      2      2     -1   
1   2     120000  female  university         2   26     -1      2      0   
2   3      90000  female  university         2   34      0      0      0   
3   4      50000  female  university         1   37      0      0      0   
4   5      50000    male  university         1   57     -1      0     -1   

   PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0     -1  ...          0          0          0         0       689         0   
1      0  ...       3272       3455       3261         0      1000      1000   
2      0  ...      14331      14948      15549      1518      1500      1000   
3      0  ...      28314      28959      29547      2000      2019      1200   
4      0  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0                     default  
1      1000         0      2000                     default  
2      1000      1000      5000                 not default  
3      1100      1069      1000                 not default  
4      9000       689       679                 not default  

[5 rows x 25 columns]

In [5]:
rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 30 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   ID                                      30000 non-null  int64
 1   LIMIT_BAL                               30000 non-null  int64
 2   MARRIAGE                                30000 non-null  int64
 3   AGE                                     30000 non-null  int64
 4   PAY_0                                   30000 non-null  int64
 5   PAY_2                                   30000 non-null  int64
 6   PAY_3                                   30000 non-null  int64
 7   PAY_4                                   30000 non-null  int64
 8   PAY_5                                   30000 non-null  int64
 9   PAY_6                                   30000 non-null  int64
 10  BILL_AMT1                               30000 non-null  int64
 11  BILL_AMT2      

In [4]:
rawData = pd.get_dummies(rawData)
rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 30 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   ID                                      30000 non-null  int64
 1   LIMIT_BAL                               30000 non-null  int64
 2   MARRIAGE                                30000 non-null  int64
 3   AGE                                     30000 non-null  int64
 4   PAY_0                                   30000 non-null  int64
 5   PAY_2                                   30000 non-null  int64
 6   PAY_3                                   30000 non-null  int64
 7   PAY_4                                   30000 non-null  int64
 8   PAY_5                                   30000 non-null  int64
 9   PAY_6                                   30000 non-null  int64
 10  BILL_AMT1                               30000 non-null  int64
 11  BILL_AMT2      

In [6]:
#Testing regression with default as the dependent variable
X0 = rawData.iloc[:,0:27]
print('Summary of feature sample')
X0.head()

Summary of feature sample


ID  LIMIT_BAL  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  \
0   1      20000         1   24      2      2     -1     -1     -2     -2   
1   2     120000         2   26     -1      2      0      0      0      2   
2   3      90000         2   34      0      0      0      0      0      0   
3   4      50000         1   37      0      0      0      0      0      0   
4   5      50000         1   57     -1      0     -1      0      0      0   

   ...  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  SEX_female  \
0  ...       689         0         0         0         0           1   
1  ...      1000      1000      1000         0      2000           1   
2  ...      1500      1000      1000      1000      5000           1   
3  ...      2019      1200      1100      1069      1000           1   
4  ...     36681     10000      9000       689       679           0   

   SEX_male  EDUCATION_graduate school  EDUCATION_high school  EDUCATION_other  
0         0                          0                      0                0  
1         0                          0                      0                0  
2         0                          0                      0                0  
3         0                          0                      0                0  
4         1                          0                      0                0  

[5 rows x 27 columns]

In [7]:
y0=rawData['default payment next month_default']

In [8]:
print(y0)

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: default payment next month_default, Length: 30000, dtype: uint8


In [9]:
model0 = LinearRegression(n_jobs=10)

In [10]:
X0_train, X0_test, y0_train, y0_test = train_test_split(X0, y0, test_size = .30, random_state = 123)
algo0 = DecisionTreeClassifier()
model00 = algo0.fit(X0_train,y0_train)

In [11]:
print(cross_val_score(model0, X0, y0, cv=3)) 

[0.10525781 0.13310298 0.12459072]


In [12]:
print(cross_val_score(model0, X0_train, y0_train, cv=3)) 

[0.11169482 0.13377469 0.12272578]


In [13]:
algosClass0 = []

algosClass0.append(('Random Forest Regressor',RandomForestRegressor()))

algosClass0.append(('Linear Regression',LinearRegression()))

algosClass0.append(('Support Vector Regression',SVR()))

algosClass00 = []
algosClass00.append(('Random Forest Classifier', RandomForestClassifier()))
algosClass00.append(('Decision Tree Classifier', DecisionTreeClassifier()))
algosClass00.append(('Gradient Boosting Classifier', GradientBoostingClassifier()))
algosClass00.append(('AdaBoostClassifier',AdaBoostClassifier()))

In [14]:
results0 = []
names0 = []

results00 = []
names00 = []
for name0, model0 in algosClass0:
    result0 = cross_val_score(model0, X0,y0, cv=3, scoring='r2')
    names0.append(name0)
    results0.append(result0)
    
for name00, model00 in algosClass00:
    result00 = cross_val_score(model00, X0,y0, cv=3, scoring='accuracy')
    names0.append(name00)
    results0.append(result00)  

In [15]:
for i in range(len(names0)):
    print(names0[i],results0[i].mean())
    

Random Forest Regressor 0.07742135048743733
Linear Regression 0.12098383548904572
Support Vector Regression -0.0851574683713469
Random Forest Classifier 0.6164000000000001
Decision Tree Classifier 0.5519
Gradient Boosting Classifier 0.6007000000000001
AdaBoostClassifier 0.6029666666666667


In [16]:
#removing columns for less clutter
rawData.drop(columns=['EDUCATION_graduate school','EDUCATION_high school','EDUCATION_other',
                     'EDUCATION_university','SEX_male','SEX_female','AGE','MARRIAGE'], inplace =True, axis =1)

In [17]:
rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 22 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   ID                                      30000 non-null  int64
 1   LIMIT_BAL                               30000 non-null  int64
 2   PAY_0                                   30000 non-null  int64
 3   PAY_2                                   30000 non-null  int64
 4   PAY_3                                   30000 non-null  int64
 5   PAY_4                                   30000 non-null  int64
 6   PAY_5                                   30000 non-null  int64
 7   PAY_6                                   30000 non-null  int64
 8   BILL_AMT1                               30000 non-null  int64
 9   BILL_AMT2                               30000 non-null  int64
 10  BILL_AMT3                               30000 non-null  int64
 11  BILL_AMT4      

In [18]:
#Testing regression and classification models for default payment as as the dependent variable
#after removing some columns
X = rawData.iloc[:,0:19]
print('Summary of feature sample')
X.head()

Summary of feature sample


ID  LIMIT_BAL  PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  BILL_AMT1  \
0   1      20000      2      2     -1     -1     -2     -2       3913   
1   2     120000     -1      2      0      0      0      2       2682   
2   3      90000      0      0      0      0      0      0      29239   
3   4      50000      0      0      0      0      0      0      46990   
4   5      50000     -1      0     -1      0      0      0       8617   

   BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0       3102        689          0          0          0         0       689   
1       1725       2682       3272       3455       3261         0      1000   
2      14027      13559      14331      14948      15549      1518      1500   
3      48233      49291      28314      28959      29547      2000      2019   
4       5670      35835      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  
0         0         0         0  
1      1000      1000         0  
2      1000      1000      1000  
3      1200      1100      1069  
4     10000      9000       689

In [19]:
y=rawData['default payment next month_default']

In [20]:
print(y)

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: default payment next month_default, Length: 30000, dtype: uint8


In [21]:
#the regression model 
model = LinearRegression(n_jobs=10)

In [22]:
#the classification model from course 1 task 2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .30, random_state = 123)
algo = DecisionTreeClassifier()
model1 = algo.fit(X_train,y_train)

In [23]:
print(cross_val_score(model, X, y, cv=3)) 

[0.10246194 0.1308356  0.12065829]


In [24]:
print(cross_val_score(model1, X_train, y_train, cv=3)) 

[0.72471429 0.72857143 0.71642857]


In [25]:
#choosing the right model by testing different results
algosClass = []

algosClass.append(('Random Forest Regressor',RandomForestRegressor()))

algosClass.append(('Linear Regression',LinearRegression()))

algosClass.append(('Support Vector Regression',SVR()))

algosClass1 = []
algosClass1.append(('Random Forest Classifier', RandomForestClassifier()))
algosClass1.append(('Decision Tree Classifier', DecisionTreeClassifier()))
algosClass1.append(('Gradient Boosting Classifier', GradientBoostingClassifier()))
algosClass1.append(('AdaBoostClassifier',AdaBoostClassifier()))



In [26]:
results = []
names = []

results1 = []
names1 = []
for name, model in algosClass:
    result = cross_val_score(model, X,y, cv=3, scoring='r2')
    names.append(name)
    results.append(result)
    
for name1, model1 in algosClass1:
    result1 = cross_val_score(model1, X,y, cv=3, scoring='accuracy')
    names.append(name1)
    results.append(result1)    

In [27]:
for i in range(len(names)):
    print(names[i],results[i].mean())
    


Random Forest Regressor 0.0869322926031797
Linear Regression 0.11798527468507754
Support Vector Regression -0.0853667463741475
Random Forest Classifier 0.6140333333333333
Decision Tree Classifier 0.5469333333333334
Gradient Boosting Classifier 0.5999
AdaBoostClassifier 0.6016333333333334


In [28]:
#Testing regression models with Limit Balance as the dependent variable
X1 = rawData[['PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6','BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5'
            ,'BILL_AMT6','PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6','default payment next month_default'
            ,'default payment next month_not default']]
print('Summary of feature sample')
X1.head()

Summary of feature sample


PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  \
0      2      2     -1     -1     -2     -2       3913       3102        689   
1     -1      2      0      0      0      2       2682       1725       2682   
2      0      0      0      0      0      0      29239      14027      13559   
3      0      0      0      0      0      0      46990      48233      49291   
4     -1      0     -1      0      0      0       8617       5670      35835   

   BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  \
0          0          0          0         0       689         0         0   
1       3272       3455       3261         0      1000      1000      1000   
2      14331      14948      15549      1518      1500      1000      1000   
3      28314      28959      29547      2000      2019      1200      1100   
4      20940      19146      19131      2000     36681     10000      9000   

   PAY_AMT5  PAY_AMT6  default payment next month_default  \
0         0         0                                   1   
1         0      2000                                   1   
2      1000      5000                                   0   
3      1069      1000                                   0   
4       689       679                                   0   

   default payment next month_not default  
0                                       0  
1                                       0  
2                                       1  
3                                       1  
4                                       1

In [29]:
y1= rawData['LIMIT_BAL']

In [30]:
print(y1)

0         20000
1        120000
2         90000
3         50000
4         50000
          ...  
29995    220000
29996    150000
29997     30000
29998     80000
29999     50000
Name: LIMIT_BAL, Length: 30000, dtype: int64


In [31]:
model2 = LinearRegression(n_jobs=10).fit(X1,y1)
model2.score(X1,y1)

#X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = .30, random_state = 123)
#algo2 = DecisionTreeClassifier()
#model22 = algo2.fit(X1_train,y1_train)
#model22= DecisionTreeClassifier()

0.31304169591963316

In [32]:
#Testing different models
algosClass2 = []

algosClass2.append(('Random Forest Regressor',RandomForestRegressor()))

algosClass2.append(('Linear Regression',LinearRegression()))

algosClass2.append(('Support Vector Regression',SVR()))

#algosClass22 = []
#algosClass22.append(('Random Forest Classifier', RandomForestClassifier()))
#algosClass22.append(('Decision Tree Classifier', DecisionTreeClassifier()))
#algosClass22.append(('Gradient Boosting Classifier', GradientBoostingClassifier()))
#algosClass22.append(('AdaBoostClassifier',AdaBoostClassifier()))

In [33]:
results2 = []
names2 = []

#results22 = []
#names22 = []

for name, model2 in algosClass2:
    result2 = cross_val_score(model2, X1,y1, cv=3, scoring='r2')
    names2.append(name)
    results2.append(result2)
    
#for name, model22 in algosClass22:
#   result22 = cross_val_score(model22, X1,y1, cv=3, scoring='accuracy')
#   names22.append(name)
#    results22.append(result22)   

In [34]:
for i in range(len(names2)):
    print(names2[i],results2[i].mean())

Random Forest Regressor 0.4117158774707552
Linear Regression 0.30278768143658047
Support Vector Regression -0.050319849599297584


In [35]:
#binning limit balance and using that as the dependent variable
print (np.median(rawData['LIMIT_BAL']))
print (np.max(rawData['LIMIT_BAL']))

140000.0
1000000


In [36]:
plt.hist(rawData['LIMIT_BAL'])
plt.show()

In [37]:
#trying a few bins just to see accuracy
lim_array = (0,150000,1000000)

In [38]:
rawData['lim_array'] = pd.cut(rawData['LIMIT_BAL'],lim_array,labels = False )
rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   ID                                      30000 non-null  int64
 1   LIMIT_BAL                               30000 non-null  int64
 2   PAY_0                                   30000 non-null  int64
 3   PAY_2                                   30000 non-null  int64
 4   PAY_3                                   30000 non-null  int64
 5   PAY_4                                   30000 non-null  int64
 6   PAY_5                                   30000 non-null  int64
 7   PAY_6                                   30000 non-null  int64
 8   BILL_AMT1                               30000 non-null  int64
 9   BILL_AMT2                               30000 non-null  int64
 10  BILL_AMT3                               30000 non-null  int64
 11  BILL_AMT4      

In [39]:
X2=rawData[['PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6','BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5'
            ,'BILL_AMT6','PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6','default payment next month_default'
            ,'default payment next month_not default']]
print('Summary of feature sample')
X2.head()

Summary of feature sample


PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  \
0      2      2     -1     -1     -2     -2       3913       3102        689   
1     -1      2      0      0      0      2       2682       1725       2682   
2      0      0      0      0      0      0      29239      14027      13559   
3      0      0      0      0      0      0      46990      48233      49291   
4     -1      0     -1      0      0      0       8617       5670      35835   

   BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  \
0          0          0          0         0       689         0         0   
1       3272       3455       3261         0      1000      1000      1000   
2      14331      14948      15549      1518      1500      1000      1000   
3      28314      28959      29547      2000      2019      1200      1100   
4      20940      19146      19131      2000     36681     10000      9000   

   PAY_AMT5  PAY_AMT6  default payment next month_default  \
0         0         0                                   1   
1         0      2000                                   1   
2      1000      5000                                   0   
3      1069      1000                                   0   
4       689       679                                   0   

   default payment next month_not default  
0                                       0  
1                                       0  
2                                       1  
3                                       1  
4                                       1

In [40]:
y2=rawData['lim_array']
print(y2)

0        0
1        0
2        0
3        0
4        0
        ..
29995    1
29996    0
29997    0
29998    0
29999    0
Name: lim_array, Length: 30000, dtype: int64


In [41]:
#the population looks similar ~16k and ~14k at each bin
plt.hist(rawData['lim_array'])
plt.show()

In [42]:
model3 = LinearRegression(n_jobs=10).fit(X2,y2)
model3.score(X2,y2)

0.23426154770879004

In [43]:
algosClass3 = []

algosClass3.append(('Random Forest Regressor',RandomForestRegressor()))

algosClass3.append(('Linear Regression',LinearRegression()))

algosClass3.append(('Support Vector Regression',SVR()))


In [44]:
results3 = []
names3 = []
for name3, model3 in algosClass3:
    result3 = cross_val_score(model3, X2,y2, cv=3, scoring='r2')
    names3.append(name3)
    results3.append(result3)
    


In [45]:
for i in range(len(names3)):
    print(names3[i],results3[i].mean())        

Random Forest Regressor 0.3669299058950351
Linear Regression 0.22713826779689747
Support Vector Regression 0.2013340076888959


In [46]:
#Highest score was RandomForest Regressor for the regression models
#Limit bal was the dependent variable
algo=RandomForestRegressor()

In [47]:
#Train/Test Split 
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size = .30, random_state = 123)

In [48]:
model = algo.fit(X_train,y_train)

In [49]:
predictions = model.predict(X_test)

In [50]:
rmse = sqrt(mean_squared_error(y_test, predictions))

In [51]:
predRsquared = r2_score(y_test,predictions)

In [52]:
#Make Predictions
predictions = model.predict(X_test)
predRsquared = r2_score(y_test,predictions)
rmse = sqrt(mean_squared_error(y_test, predictions))
print('R Squared: %.3f' % predRsquared)
print('RMSE: %.3f' % rmse)

R Squared: 0.408
RMSE: 99017.353


In [53]:
plt.scatter(y_test, predictions, alpha = 0.5)
plt.xlabel('Ground Truth')
plt.ylabel('Predictions')
plt.show();

In [78]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = .30, random_state = 123)

rf = RandomForestRegressor(n_estimators=100)
rf.fit(X1_train, y1_train)

RandomForestRegressor()

In [59]:
#feature_names = [f"feature {i}" for i in range(X.shape[1])]

In [77]:
plt.barh(chartlabels.columns,rf.feature_importances_)
plt.show()

In [64]:
rf.feature_importances_

array([0.0176879 , 0.08056705, 0.01986447, 0.00770594, 0.00606684,
       0.00912771, 0.12045823, 0.04849996, 0.04572476, 0.04224037,
       0.05297968, 0.0534747 , 0.05640814, 0.11788291, 0.06950526,
       0.0516145 , 0.06039107, 0.13202175, 0.00386244, 0.00391632])

In [68]:
rawData.loc[0]

ID                                            1
LIMIT_BAL                                 20000
PAY_0                                         2
PAY_2                                         2
PAY_3                                        -1
PAY_4                                        -1
PAY_5                                        -2
PAY_6                                        -2
BILL_AMT1                                  3913
BILL_AMT2                                  3102
BILL_AMT3                                   689
BILL_AMT4                                     0
BILL_AMT5                                     0
BILL_AMT6                                     0
PAY_AMT1                                      0
PAY_AMT2                                    689
PAY_AMT3                                      0
PAY_AMT4                                      0
PAY_AMT5                                      0
PAY_AMT6                                      0
default payment next month_default      

In [69]:
rawData.columns

Index(['ID', 'LIMIT_BAL', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6',
       'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5',
       'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5',
       'PAY_AMT6', 'default payment next month_default',
       'default payment next month_not default', 'lim_array'],
      dtype='object')

In [71]:
chartlabels = rawData[['PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6','BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5'
            ,'BILL_AMT6','PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6','default payment next month_default'
            ,'default payment next month_not default']]